
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = -1
y = -1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mode = "~Alt"
mods = "Control|Shift"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = false
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[general]
import = [
    "~/.config/alacritty/themes/blood_moon.toml"
]
