# vim: foldmethod=marker ft=tmux
# {{{1 Appearance
if-shell '[ -n "$SSH_CONNECTION" ]' {
  %hidden accent_color=pink
} { %hidden accent_color=colour113 }
set-window-option -g window-style 'bg=#101010'
set-window-option -g window-active-style 'bg=#151515'
set -g pane-border-style fg=colour238,bg=#101010
set -g pane-active-border-style fg=${accent_color},bg=#151515
# {{{2 Status
# {{{3 Prefix highlight
set -g @prefix_highlight_empty_prompt   '      '
set -g @prefix_highlight_prefix_prompt  'Wait'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_prompt    'Copy'
set -g @prefix_highlight_copy_mode_attr 'fg=black,bg=yellow'
# I almost never use sync mode, so it would be good to see if I'm there
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_sync_prompt    'Sync'
set -g @prefix_highlight_sync_mode_attr 'fg=black,bg=red'
# {{{3 Windows list
set    -g status-justify absolute-centre
# Make widths constant with or without flags
set -w -g window-status-current-format ' #I.#W#F '
set -w -g window-status-format ' #I.#W#{?#{==:#F,},  ,#F }'
set -w -g window-status-current-style bg=default,fg=${accent_color}
# {{{3 Common status settings
set    -g status-style bg=#151515,fg=white
set    -g status-left-length 50
set    -g status-left-style fg=${accent_color}
set    -g status-left '#{prefix_highlight}#{session_name}'
# This is the default status-right without hostname
set   -g status-right-style fg=${accent_color}
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %H:%M %d-%b-%y"
