#! /bin/sh

# check if hotkey deamon is started,
# if it is, then reload the settings,
# if not, then start it
if [ -n "$( pgrep sxhkd )" ]
then
  pkill -USR1 -x sxhkd
else
  sxhkd -m -1 &
fi

picom -b --config ~/.config/picom/picom.conf

killall dunst; dunst &
feh --bg-scale ~/Pictures/Wallpaper/wall.jpg

~/.config/polybar/launch.sh

telegram-desktop &
skypeforlinux &

killall alttab; exec alttab -w 1 -mk Super_L -kk grave -fg "#d58681" -bg "#4a4a4a" -frame "#eb564d" -t 128x150 -i 127x64 &

