#! /bin/sh

# First of all, I want monitor configuration set up
sh ~/.config/bspwm/monitor-config.sh

xsetroot -cursor_name left_ptr
setxkbmap -option grp:caps_toggle -option grp_led:caps us,ru &

bspc config border_width         1

bspc config window_gap           10

bspc config focused_border_color "#00bfff"
bspc config presel_feedback_color "#888888"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Peek state=floating
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop state=floating # desktop=chat
bspc rule -a Skype state=floating # desktop=chat

wmname compiz
sh ~/.config/bspwm/autostart
