#! /bin/sh

# First of all, I want monitor configuration set up
if xrandr | grep -q 'HDMI2 connected'
  then
    xrandr --output HDMI2 --right-of eDP1 --primary
    bspc monitor HDMI2 -d 1 2 3 4 5 6 7 8
    bspc monitor eDP1 -d 9 10
    bspc wm --reorder-monitors HDMI2 eDP1
  else
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

xsetroot -cursor_name left_ptr
setxkbmap -option grp:caps_toggle -option grp_led:caps us,ru &

bspc config border_width         1

bspc config window_gap           10

bspc config focused_border_color "#00bfff"
bspc config presel_feedback_color "#888888"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Peek state=floating
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Skype desktop='^9'
bspc rule -a Code desktop='^1'

wmname compiz
